### PR TITLE
Rectified the issue of non-responsiveness in mobile version

### LINKED ISSUE #81: [Bug]: The website is not responsive in mobile view
### Give a brief about the bug ✍️

As we are opening the website in the laptop it is working fine, but as I open it in mobile , it is not responsive. Hence ,it's a major issue for mobile users.

https://github.com/GameSphere-MultiPlayer/Squard-line/assets/130597958/a671f3f8-878e-4a88-b0ea-580be41ce433

### What is the expected behavior? 🤔

In both laptop and mobile view , the game must be appear on the center of the screen so that user can play the game.

### Provide step by step information reproduce the bug 📄

Step-1: Go to the home page 
Step-2: Change the view to mobile view
Step-3: The game will not align at the center.
Step-4: Simply go to the style component in the index.html file.
Step-5: Add external CSS in order to justify the content at the center.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by Garvanand**
## PR Description 📜
Rectified the issue of non-responsiveness in the mobile version
Fixes #81 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸
image
Screenshot 2024-06-07 175023

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by Garvanand** [comment]
KIndly mark this contribution under gssoc'24

**Comment by Durgesh4993** [comment]
Please resolve conflict file

**Comment by Garvanand** [comment]
@Durgesh4993 I have resolved all conflicts and the code is working absolutely fine

**Review by Durgesh4993 — COMMENTED** [review]
reolve conflict file and add a demo video

**Comment by Garvanand** [comment]
https://drive.google.com/file/d/1Kwxpd0hTuTFqWW9wMuqHwFXZYlksyoE0/view?usp=sharing

The demo video link of working in mobile mode

**Pull request merged**
