### PR TITLE
Added the X icon in social links.

### LINKED ISSUE #88: [New Feature]: Inclusion of X(formerly twitter) icon in footer section
### 🎮 feature Request

In the GameSphere-Multiplayer,  the footer section contains GitHub, linked in, and other logos.
If the X(formerly Twitter) icon is also added, the social links will be completed.

### Point down the features

* Inclusion of X's icon for the social link activities through the X platform
* This would increase the number of players since X is a large social community.
Screenshot 2024-05-28 230133

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by swetha5157**
## PR Description 📜
Fixes #88

<hr>
 
## Mark the task you have completed ✅
- In the GameSphere-Multiplayer, the X icon(formerly Twitter) is added.
- This would increase the number of players since X is a large social community.

Point down the features

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

Screenshot 2024-06-01 144713

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by swetha5157** [comment]
Raised PR. Kindly check it @Durgesh4993

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
Remove last icon

**Comment by swetha5157** [comment]
OK @Durgesh4993 I will change it

**Comment by swetha5157** [comment]
I've removed the last icon kindly check it @Durgesh4993 
Screenshot 2024-06-05 090144

**Comment by swetha5157** [comment]
Changes made as suggested kindly merge the pr @Durgesh4993

**Comment by swetha5157** [comment]
Kindly merge the pr @Durgesh4993.

**Comment by swetha5157** [comment]
Made necessary changes..kindly merge it @Durgesh4993

**Comment by swetha5157** [comment]
I have made the changes as suggested why is it not merged ? Kindly clarify @Durgesh4993

**Pull request closed without merging**
