### PR TITLE
Modified to correct mail icon

### LINKED ISSUE #156: [Bug]: Mail icon is not correct
### Give a brief about the bug ✍️

real mail icon should be placed

### What is the expected behavior? 🤔

Instead of mail icon it is showing square

### Provide step by step information reproduce the bug 📄

In the social media icons section mail icon is not correct

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by vinay-reddy31**
## PR Description 📜

Bug: Mail icon is not correct
Modified the correct mail icon
Fixes #156 

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for review.

<hr>
Before:

image

After:
image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Review by Durgesh4993 — APPROVED** [review]
Approved

**Comment by Durgesh4993** [comment]
@vinay-reddy31 resolve conflicting files

**Comment by vinay-reddy31** [comment]
Resolved Conflicts

**Review by Durgesh4993 — APPROVED** [review]
Approved

**Pull request merged**
