### PR TITLE
undo and restart buttons 

### LINKED ISSUE #51: [New Feature]: Add undo and restart functions
### 🎮 feature Request

If a player wants to reverse their position in a game to improve their score, they may need to  undo there position of the game

### Point down the features

feature points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by P-lavanya16**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #51 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Review by Durgesh4993 — COMMENTED** [review]
Add a demo video and resolve conflict file

**Comment by Durgesh4993** [comment]
@P-lavanya16 Add a demo video

**Comment by P-lavanya16** [comment]
Uploading WhatsApp Video 2024-06-05 at 18.20.38_3ba1f0cc.mp4…

Demo video

**Comment by P-lavanya16** [comment]
https://github.com/ChromeGaming/Squard-line/assets/145569662/8833ee58-4461-4740-8cb5-3f3a68bf97bd

demo video

**Comment by P-lavanya16** [comment]
@Durgesh4993 please kindly review and merge it!!

**Pull request merged**
