### PR TITLE
Home page added

### LINKED ISSUE #82: Feature Request: Introduction of Squard-line Homepage
### feature logic and basic description:
We propose implementing a dedicated homepage for Squard-line, our flagship game. This homepage will serve as a central hub for players to access essential game information, interesting facts, a high scores leaderboard, and a section redirecting to the main game page for further exploration.

### feature points:
**Game Information Section:** The homepage will provide a brief overview of Squard-line, including its storyline, gameplay mechanics, and key features. This section aims to give players a quick understanding of what the game entails and why it's worth playing.

**Fun Facts Segment:** Players will discover intriguing facts about Squard-line, such as development insights, hidden secrets within the game, and notable achievements. These fun facts add an element of surprise and entertainment for players, encouraging them to explore the game further.

**High Scores Leaderboard:** A prominent feature of the homepage will be the leaderboard showcasing the highest scores achieved by players. This leaderboard fosters healthy competition among players, motivating them to improve their skills and strive for the top spots.

**Main Game Page Section:** An additional section will provide a direct link to the main game page, allowing players to seamlessly transition to the full game experience. This ensures that players have easy access to the game itself, where they can dive deeper into gameplay and engage with additional features.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by Ayushvishwakarma04**
## PR Description 📜

I have implemented a dedicated homepage for Squard-line, the flagship game. This homepage will serve as a central hub for players to access essential game information, interesting facts, a high scores leaderboard, and a section redirecting to the main game page for further exploration.
Fixes #82 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by Ayushvishwakarma04** [comment]
This task requires significantly more effort and complexity than other issues assigned to GSSoC Level 2. Could you please assign it to GSSoC Level 3? Thank you!

**Comment by Durgesh4993** [comment]
@Ayushvishwakarma04 Make it resposive & add some animations

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
Remove screenshot from PR

**Comment by Ayushvishwakarma04** [comment]
I have added responsiveness and animation to the homepage of Squard-lines and removed the screenshots as discussed. The homepage now adjusts seamlessly to different screen sizes, providing a better user experience across devices. Additionally, the animations enhance the visual appeal and interactivity of the page. Let me know if there are any further changes or improvements needed!

**Review by Durgesh4993 — APPROVED** [review]
Approved

**Pull request merged**
